apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: LoadBalancer
  selector:
    app: static-website
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: static-website

  
